Extension/Routing and I18N
rishabh-vinsol/depot-app pull request #10
Opened 2023-04-26 05:35 UTC by rishabh-vinsol

2023-04-26 13:26 UTC, himanshumishra31 requested changes

2023-04-26 13:26 UTC, himanshumishra31 commented on test/mailers/previews/order_mailer_preview.rb
> +    OrderMailer.with(order: Order.last).received
send only id in mailer and fetch order there

2023-04-26 13:26 UTC, himanshumishra31 commented on app/models/user.rb
> +    "English" => "en",
use new syntax

2023-04-26 13:26 UTC, himanshumishra31 commented on app/models/user.rb
> +    "Spanish" => "es",
use integers for enum

2023-04-27 08:16 UTC, rishabh-vinsol commented on app/models/user.rb
> +    "Spanish" => "es",
Sir I have used string here because I am using language directly to set the language of errors and flash messages. If I use Integers here I would have to use the hash like
`enum language: {
    en: 0,
    es: 1
}`
which would be difficult for user to enter

2023-05-02 10:41 UTC, merged